[profile.default]
src = "src"
out = "out"
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read", path = "./"}]



remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
